/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.thin;

import org.junit.jupiter.api.Test;

class MainTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
