/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.thin;

public class Main {

    public static void main(String[] args) {
        UTM utm = new UTM();
        utm.start();
    }
}
